module.exports = {
  MODULES: {
    APPOINTMENT: "APPOINTMENT",
    CONTACT: "CONTACT",
    DOCTOR: "DOCTOR",
    DIAGNOSTIC: "DIAGNOSTIC",
    GENERAL: "GENERAL",
  },

  EVENTS: {
    APPOINTMENT_BOOKED: "APPOINTMENT_BOOKED",
    APPOINTMENT_CONFIRMED: "APPOINTMENT_CONFIRMED",
    APPOINTMENT_CANCELLED: "APPOINTMENT_CANCELLED",
    APPOINTMENT_REMARK: "APPOINTMENT_REMARK",
    CONTACT_ENQUIRY: "CONTACT_ENQUIRY",
  },

  CHANNELS: {
    EMAIL: "Email",
    WHATSAPP: "WhatsApp",
    SMS: "SMS",
  },

  STATUS: {
    PENDING: "Pending",
    SENT: "Sent",
    FAILED: "Failed",
  },
};
